[project]
name = "security-system"
version = "0.1.0"
dependencies = [
    "mkdocs>=1.6.1",
]

[tool.uv.sources]
server = { workspace = true }

[tool.uv.workspace]
members = [
    "server",
]

exclude = ["application", "docs"]
